import requests as rq
import json
import os
from datetime import datetime
from dotenv import load_dotenv
from util.functions import *


LIMITED = [
    "PET_SKIN_ENDERMAN",
    "SUPERIOR_BABY",
    "PET_SKIN_RABBIT",
    "DIVER_PUFFER",
    "REAPER_SPIRIT",
    "PET_SKIN_ROCK_THINKING",
    "PET_SKIN_ROCK_LAUGH",
    "PET_SKIN_ROCK_SMILE",
    "PET_SKIN_ROCK_EMBARRASSED",
    "PET_SKIN_ROCK_DERP",
    "PET_SKIN_ROCK_COOL",
    "MASTIFF_PUPPY",
    "PET_SKIN_GUARDIAN",
    "PERFECT_FORGE",
    "FROZEN_BLAZE_ICICLE",
    "PET_SKIN_TIGER_TWILIGHT",
    "TARANTULA_BLACK_WIDOW",
    "STRONG_BABY",
    "HOLY_BABY",
    "PROTECTOR_BABY",
    "OLD_BABY",
    "WISE_BABY",
    "YOUNG_BABY",
    "UNSTABLE_BABY",
    "PET_SKIN_SHEEP_BLACK",
    "PET_SKIN_SHEEP_PINK",
    "PET_SKIN_SHEEP_LIGHT_BLUE",
    "PET_SKIN_SHEEP_PURPLE",
    "PET_SKIN_SHEEP_LIGHT_GREEN",
    "PET_SKIN_SHEEP_WHITE",
    "PET_SKIN_WITHER",
    "PET_SKIN_SILVERFISH",
    "SUPERIOR_SHIMMER",
    "PET_SKIN_ELEPHANT_PINK",
    "PET_SKIN_ELEPHANT_BLUE",
    "PET_SKIN_ELEPHANT_ORANGE",
    "PET_SKIN_YETI_GROWN_UP",
    "PET_SKIN_JERRY_RED_ELF",
    "PET_SKIN_JERRY_GREEN_ELF",
    "SNOW_SNOWGLOBE",
    "PET_SKIN_SHEEP_NEON_BLUE",
    "PET_SKIN_SHEEP_NEON_RED",
    "PET_SKIN_SHEEP_NEON_YELLOW",
    "PET_SKIN_SHEEP_NEON_GREEN",
    "PET_SKIN_MONKEY_GOLDEN",
    "PET_SKIN_SILVERFISH_FOSSILIZED",
    "PET_SKIN_HORSE_ZOMBIE",
    "PET_SKIN_DRAGON_NEON_BLUE",
    "PET_SKIN_DRAGON_NEON_RED",
    "PET_SKIN_DRAGON_NEON_PURPLE",
    "PET_SKIN_ELEPHANT_GREEN",
    "PET_SKIN_ELEPHANT_RED",
    "PET_SKIN_ELEPHANT_PURPLE",
    "ENDERPACK",
    "PET_SKIN_WHALE_ORCA",
    "PET_SKIN_ELEPHANT_MONOCHROME",
    "SHADOW_ASSASSIN_CRIMSON",
    "SHADOW_ASSASSIN_MAUVE",
    "SHADOW_ASSASSIN_ADMIRAL",
    "GREEN_EGG",
    "PET_SKIN_CHICKEN_BABY_CHICK",
    "PURPLE_EGG",
    "BLUE_EGG",
    "PET_SKIN_RABBIT_ROSE",
    "PET_SKIN_RABBIT_AQUAMARINE",
    "PET_SKIN_BLACK_CAT_ONYX",
    "PET_SKIN_BLACK_CAT_IVORY",
    "PET_SKIN_MONKEY_GORILLA",
    "PET_SKIN_ENDERMITE_RADIANT",
    "PET_SKIN_DRAGON_PASTEL",
    "UNSTABLE_SHIMMER",
    "STRONG_SHIMMER",
    "YOUNG_SHIMMER",
    "WISE_SHIMMER",
    "OLD_SHIMMER",
    "HOLY_SHIMMER",
    "PROTECTOR_SHIMMER",
    "PET_SKIN_WOLF",
    "PET_SKIN_HOUND_BEAGLE",
    "PET_SKIN_SQUID_GLOW",
    "PET_SKIN_TIGER_SABER_TOOTH",
    "PET_SKIN_PARROT_GOLD_MACAW",
    "PET_SKIN_BAT_VAMPIRE",
    "PET_SKIN_PHOENIX_ICE",
    "PET_SKIN_OCELOT_SNOW_TIGER",
    "PET_SKIN_BLAZE_FROZEN",
    "PET_SKIN_DOLPHIN_SNUBFIN",
    "PET_SKIN_DOLPHIN_SNUBNOSE_RED",
    "PET_SKIN_DOLPHIN_SNUBNOSE_PURPLE",
    "PET_SKIN_DOLPHIN_SNUBNOSE_GREEN",
    "PET_SKIN_TIGER_GOLDEN",
    "PET_SKIN_ARMADILLO_ENCHANTED",
    "PET_SKIN_ARMADILLO_SEAFOAM",
    "PET_SKIN_JERRY_HANDSOME",
    "PET_SKIN_KUUDRA_LOYALTY",
    "TRUE_WARDEN",
    "PET_SKIN_ENDERMAN_XENON",
    "PET_SKIN_ENDERMAN_NEON",
    "PET_SKIN_BAL_INFERNO",
    "PET_SKIN_MEGALODON_BABY",
    "PET_SKIN_ENDER_DRAGON_UNDEAD",
    "PET_SKIN_BEE_RGBEE",
    "PET_SKIN_JELLYFISH_LUMINESCENT",
    "PET_SKIN_GOLDEN_DRAGON_ANUBIS",
    "PET_SKIN_SHEEP_BLACK_WOOLY",
    "PET_SKIN_SHEEP_CHROMA_WOOLY",
    "PET_SKIN_SHEEP_WHITE_WOOLY",
    "PET_SKIN_MOOSHROOM_COW_MOOCELIUM",
    "PET_SKIN_SNOWMAN_ICE_GOLEM",
    "PET_SKIN_TIGER_NEON",
    "PET_SKIN_CHICKEN_TURKEY",
    "NECRON_CELESTIAL",
    "MAXOR_CELESTIAL",
    "STORM_CELESTIAL",
    "GOLDOR_CELESTIAL",
    "PENGUIN_BACKPACK",
    "REINDEER_BACKPACK",
    "PET_SKIN_GRIFFIN_REINDRAKE",
    "BABYSEAL_BACKPACK",
    "PET_SKIN_REINDEER_AURORA",
    "WITHER_GOGGLES_CYBERPUNK",
    "WITHER_GOGGLES_CELESTIAL",
    "LUNAR_RABBIT_HAT",
    "PET_SKIN_RABBIT_LUNAR",
    "PET_SKIN_SCATHA_ALBINO",
    "PET_SKIN_SCATHA_GOLDEN",
    "PET_SKIN_SCATHA_DARK",
    "FROG_BARN_SKIN",
    "GLOWING_GRAPE_FLUX",
    "GOLDEN_APPLE_FLUX",
    "GLISTENING_MELON_FLUX",
    "JERRY_BARN_SKIN",
    "PET_SKIN_AMMONITE_NATURAL",
    "PET_SKIN_AMMONITE_MAGMA",
    "SHADOW_ASSASSIN_SLY_FOX",
    "PINWHEEL_HOUSE_BARN_SKIN",
    "PET_SKIN_WHALE_COSMIC",
    "PET_SKIN_MONKEY_LEMUR",
    "PIRATE_BOMB_FLUX",
    "PET_SKIN_PARROT_BUCCANEER",
    "PET_SKIN_ENDER_DRAGON_BABY_BLUE",
    "DRAGON_EGG_BACKPACK",
    "PET_SKIN_ENDER_DRAGON_BABY",
    "MUSHROOM_BARN_SKIN",
    "FERMENTO_BLOOM",
    "FERMENTO_LEAF",
    "REAPER_RED_ONI_MASK",
    "REAPER_BLUE_ONI_MASK",
    "REAPER_ONI_MASK",
    "GOLDEN_ANCIENT_EGG_FLUX",
    "PET_SKIN_TURTLE_ANCIENT_GOLDEN",
    "BONZO_MASK_JESTER",
    "METEOR_MAGMA_LORD",
    "GEMSTONE_DIVAN",
    "PET_SKIN_BABY_YETI_DARK_SASQUATCH",
    "PET_SKIN_BABY_YETI_LIGHT_SASQUATCH",
    "PET_SKIN_BABY_YETI_MIDNIGHT",
    "FINAL_DESTINATION_ENDER_KNIGHT",
    "PET_SKIN_WOLF_HUSKY",
    "TARANTULA_REDBACK",
    "PET_SKIN_BAT_BONE",
    "PET_SKIN_BAT_CANDY",
    "CADUCEUS_MENDING_CROWN",
    "PET_SKIN_RAT_GYM_RAT",
    "PET_SKIN_RAT_MR_CLAWS",
    "PET_SKIN_RAT_KARATE",
    "PET_SKIN_RAT_SECRAT_SERVICE",
    "PET_SKIN_RAT_NINJA",
    "PET_SKIN_RAT_PIRATE",
    "PET_SKIN_RAT_SQUEAKHEART",
    "PET_SKIN_RAT_RAT-STRONAUT",
    "PET_SKIN_RAT_SECURATY_GUARD",
    "PET_SKIN_RAT_JUNK_RAT",
    "PET_SKIN_CHICKEN_RUBBER",
    "PET_SKIN_ENDERMAN_SUN",
    "PET_SKIN_ENDERMAN_NEBULA",
    "PET_SKIN_ENDERMAN_BLUE_MOON",
    "PET_SKIN_SLUG_AZURE_SEA_SLUG",
    "PET_SKIN_SLUG_VIOLET_SEA_SLUG",
    "PET_SKIN_SLUG_LEAF_SHEEP_SEA_SLUG",
    "PET_SKIN_SNAIL_RAINBOW",
    "PET_SKIN_FOUR_SEASONS_GRIFFIN",
    "PET_SKIN_CAT_SPACE_KITTY",
    "PET_SKIN_WOLF_DOGE",
    "PET_SKIN_ZOMBIE_SENTINEL",
    "PET_SKIN_ZOMBIE_BRAIN_FREEZE",
    "SENTINEL_WARDEN",
    "PET_SKIN_ZOMBIE_BIG_BRAIN",
    "PET_SKIN_BABY_YETI_PLUSHIE",
    "PET_SKIN_SNOWMAN_PLUSHIE",
    "MAGIC_CUBE_FLUX",
    "PET_SKIN_REINDEER_PLUSHIE",
    "PET_SKIN_ELEPHANT_BLACK_PLUSHIE",
    "PET_SKIN_ELEPHANT_GRAY_PLUSHIE",
    "PET_SKIN_ELEPHANT_BLUE_PLUSHIE",
    "PET_SKIN_ELEPHANT_COSMIC",
    "PET_SKIN_ELEPHANT_PINK_PLUSHIE",
    "PET_SKIN_MONKEY_SEE_HEAR_SPEAK",
    "PET_SKIN_GIRAFFE_SAFARI",
    "PET_SKIN_MONKEY_ASTRONAUT",
    "PET_SKIN_OCELOT_JUNGLE",
    "PET_SKIN_MITHRIL_GOLEM_CRYSTAL",
    "PET_SKIN_MITHRIL_GOLEM_CHERRY_BLOSSOM",
    "PET_SKIN_MITHRIL_GOLEM_COPPER",
    "ENRAGER",
    "TENTACLE_DYE",
]


def get_items(log: bool) -> dict:
    """
    Get the limited items from the API.

    :param: log - Whether to log the data.
    :return: A dictionary containing the limited items.
    """

    items = {}
    now = datetime.now().timestamp()

    for item in LIMITED:
        if log:
            print(f"Fetching data for {item}...")

        try:
            response = rq.get(f"https://sky.coflnet.com/api/item/price/{item}/history/full")
        except rq.exceptions.RequestException:
            if log:
                print(f"Failed to fetch data for {item}.")
            continue

        try:
            data = response.json()
            if len(data) == 0:
                continue
            items[item] = {"lbin": response.json()[-1]["avg"], "timestamp": now}
        except json.JSONDecodeError:
            if log:
                print(f"Failed to decode JSON for {item}.")
            continue

    return items


if __name__ == "__main__":
    load_dotenv()
    LOG = os.getenv("LOG") == "True"

    items = get_items(log=LOG)
    save_data(data=items, name="limited", log=LOG)
